version: '3.1'

services:

  app:
    build: C:\Users\home\projects\app\
    container_name: app
    restart: always
    depends_on:
      - db
    volumes:
    - H:\xml\in\:/var/in/
    - H:\xml\out\:/var/out/
    - H:\xml\buf\:/var/buf/
    - H:\xml\log\:/var/log/
    - H:\app:/var/app/
    ports:
    - 8080:8080

  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 666666
      MYSQL_DATABASE: training_base
    ports:
      - 3306:3306
    volumes:
      - C:\Users\home\docker_images\mysql8\files:/var/lib/mysql

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 7070:8080